ceate issues
businesskaniki/microflix pull request #29
Opened 2022-08-01 16:26 UTC by businesskaniki

### link to the issues

https://github.com/businesskaniki/microflix/issues

2022-08-01 16:33 UTC, AshakaE commented
### Hi @businesskaniki  🙋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request ❌ 

You have submitted a project, that has not listed the team members of the project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-01 18:45 UTC, businesskaniki commented
ok am not understanding what you need us to do  please guide us

2022-08-01 20:09 UTC, Rustamxon7 requested changes
Hi TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-01 20:09 UTC, Rustamxon7 commented on README.md
> -# microflix
You made a great effort on this project. However, it has one thing that needs to be completed to make your project approved.

Kindly assign the person to each task equally. 

WRONG:

<img width="358" alt="Screen Shot 2022-08-02 at 00 33 27" src="https://user-images.githubusercontent.com/69011963/182235602-60e8e575-37eb-459b-8f15-a31cec24cb7f.png">

CORRECT:

<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/69011963/182235693-06fa61d9-bb2d-4e10-ad33-b0b61e0d86f1.png">

2022-08-01 20:09 UTC, Rustamxon7 commented on README.md
> -# microflix
In a group task, you can assign both of you.

2022-08-01 20:19 UTC, businesskaniki commented
thank you very much

2022-08-02 07:58 UTC, tresorsawasawa commented
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Team;
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-02 08:32 UTC, merged